### ISSUE TITLE
Hovering over items in Ghantt Chart makes items disappears

### ISSUE THREAD

**Issue by LeisaWatkins** [projectknife/Projectfork#1088]
When I hover over an item in the Ghantt Chart it disappears.  As I go down the list, hovering over each item, they all disappear. They show up again when I refresh the page.  Any ideas on why?

**Comment by Tobes55** [comment]
I cant find a fix either, having the same issue with all templates, stuff disappears when I hover over it, anything that uses tooltip, Ive tried this #680 (comment) but having trouble getting that to work too, I have left a comment on that issue, I hope some one can help me :) Thanks

**Comment by Tobes55** [comment]
also switching off bootstrap js just disables loads of drop down menus and features so thats not a good option for me :(

**Comment by kyleledbetter** [comment]
@Tobes55 did you try adding the jQuery snippet mentioned here?  https://github.com/projectfork/Projectfork/issues/680#issuecomment-22165152

**Comment by Tobes55** [comment]
I did indeed the author of that thread very kindly came to my rescue, if anyone is interested, we had to tweak his code, as it was different elements that seem to be disappearing for me, everything with a tool tip, heres the code I ended up adding, and designs working great, and anything with a tooltip now stays on the screen when rolled over :)


jQuery(".gantt-bs-tt").live('mouseout',function() {
jQuery(".gantt-bs-tt").css("display","block"); });

jQuery(".thumbnail").live('mouseout',function() {
jQuery(".thumbnail").css("display","block"); });

jQuery(".hasTooltip").live('mouseout',function() {
jQuery(".hasTooltip").css("display",""); }); 

Thanks

**Comment by kyleledbetter** [comment]
:+1:
