### ISSUE TITLE
Easy Social integration?

### ISSUE THREAD

**Issue by ghost** [projectknife/Projectfork#1096]
Hi, hi

I notice that you have integration with CB & Jom Social

http://projectfork.net/blog/13-releases/77-cb-and-js-integration-released

Any plans for Easy Social integration?

http://stackideas.com/easysocial

best

Paul

**Comment by unitedonline** [comment]
I wonder why no one has answered in 18 months?
I am also very interested in this integration.

**Comment by jhweb** [comment]
this is just not happening, truly sad it is.
