### ISSUE TITLE
Creating Projects from a form (RSForm possibly) 

### ISSUE THREAD

**Issue by DiGwork** [projectknife/Projectfork#1119]
I would be interested to know what it would take to feed information gathered from a form tool like RSForms Pro into Projectfork to automatically create projects with milestones tasks and user assignment using that information gathered? I ask this because often the information needed to create a project might come from different people in different departments and if all the info could be gathered using RSForms Pro to set up a Virtual Job Card first then with a single action that data could be used to set up the project and all its required milestones, tasks, lists, users and documents etc.
I ask this as often it is not the displaying of the information that is the UX problem but the actual input of information. If there is a form that gathers the information in a step by step process then user training is much easier and standardisation of information capture and project setup is so much easier to achieve especially when dealing with the technically challenged.

**Comment by DiGwork** [comment]
without this plugin I am doing all the bridging between the forms filled in by the users and loading it all manually into Project fork. And I must tell you this sucks. I never intended doing so much manual process support when I selected to use Projectfork to build my clients project management interface. It has turned into a full time job that I am not being paid for. 
I really feel that Projectfork is not complete without some way to customise input interfaces. My clients staff are just too intimidated by the full PF interface. I really hoped that we could get this plugin. or at least some way of minimising what the users see. 
I love the full functionality of PF but without some way to offer the "illiterate technophobes" a simple input interface I am going to have to start looking for some other solution other than PF as I am seriously loosing man hours doing all the data capturing for my clients staff!

**Comment by DiGwork** [comment]
Is there anyone else that could possibly give me some advice on how to link results from a from created in RS-Forms to the database fields of a Project fork so that I can attempt to sovle this plugin?? Angek was very close and then he stopped all together.

**Comment by amruffatti** [comment]
Yes. I waited for Angek until my client went ballistic. Did you try using the Mappings feature in RSForm PRO? You can write directly to any ProjectFork  field, or create new ones.I ended up constructing my own client/project manager out of RSForm PRO only, plus a few regular php pages to show the milestones, and did not use ProjectFork altogether. If you're interested, I can give you access to a demo (all in Spanish). 


-------- Original Message --------
Subject: Re: [Projectfork] Creating Projects from a form (RSForm
possibly)  (#1119)

**Comment by DiGwork** [comment]
Thanks amruffatti I will try that and yes I would love to see your demo!

**Comment by amruffatti** [comment]
This is the administrative front end:
http://s261871817.onlinehome.us/demo/index.php/ingreso-2.html
Username: msimon
Password: hello

Basically, data gathered on the first forms goes on to populate subsequent forms. The demo has almost no data, so it's kind of hard to see this - and all instructions are in Spanish. So Skype me at amruffatti and I'll walk you through.

**Comment by DiGwork** [comment]
Hi Adela

Thanks
I am on course until Thursday so if it is OK with you, can I skype call 
you on Thursday to go through your demo. I am on Central Africa time (+2)
What time would suite you on Thursday?

Regards

Mark

**Comment by amruffatti** [comment]
Mark, I've replied to you via the contact form on your website.Adela


-------- Original Message --------
Subject: Re: [Projectfork] Creating Projects from a form (RSForm
possibly)  (#1119)
