### ISSUE TITLE
How to Copy / duplicate a Project

### ISSUE THREAD

**Issue by smalldragoon** [projectknife/Projectfork#1250]
Hi, 
I will have to duplicate a project around 45 times ( with diffrent users assigned at the end )
How can I do it wihtout recreating each time the project, the tasks etc....
is it possible ? maybe by SQL somewhere ? 
Any idea is wlecome if not existing in the product ( that I think unfortunatly )
Thx !
Lionel

**Comment by rexbarkdoll** [comment]
I've also noticed that Attachments don't get brought along to the new project. Would you be able to keep those attached as copies are made?

**Comment by dtf099** [comment]
Hi,
I will be out of the office until Monday, 25 May 2015. We are moving back to our premises after earthquake repairs.
Regards,
Linda

**Comment by catanddave** [comment]
Is there any way to duplicate the attachments (as asked by rexbarkdoll). I have a project template that contains lots of blank template documents against tasks. It would be great to be able to copy everything from this template into a new project.
