### ISSUE TITLE
Urgent : Automatic notifications to user groups 

### ISSUE THREAD

**Issue by erbunty** [projectknife/Projectfork#1272]
I have more than 100 client list and its very difficult to tell them to click on email subscribe button for notifications 

I want they will get notification when I have created a task or project or anything else.

Once i assigned user group then all users in that user group will get email if I have created any thing. 

Please provide solution how Can I user projectfork well other wise I have to uninstall it and looking for other component. 

Email subscribe logic is not good and fit for us 

Hope you understand well as this is very basic and critical feature.

**Comment by milosmojzis** [comment]
Does anybody have working solution for this? The auto-subscribe functionality would be very useful in the environment where the users do not work with PF on daily basis but rather sporadically - they are not informed about their assignment to the project until they log in to PF...
