### ISSUE TITLE
Time Tracking not working

### ISSUE THREAD

**Issue by jburke1** [projectknife/Projectfork#1297]
Updated to Joomla 3.3.0
Click on Time Tracking and get: 
Fatal error: Call to undefined method JApplicationAdministrator::getParams() in /home/ports987/public_html/anytimeanywherebookkeeping.com/components/com_pftime/models/timesheet.php on line 457

The code is:
456     // Params
457        $value = $app->getParams();
458       $this->setState('params', $value);
459
460        // State

Other parts of the component are working.

**Comment by angek** [comment]
was never able to reproduce this error.
