### ISSUE TITLE
Comments not working - "Invalid Token"

### ISSUE THREAD

**Issue by b16leboy** [projectknife/Projectfork#1303]
MqSQL 5.6.16; PHP 5.5.9; Apache 2.4.7
Joomla 3.3.1 (also failed on 3.3.0)
Projectfork 4.2.1 

First post of a comment to a project seems to work; all subsequent posts report "Invalid Token".

Tried a full reinstall as a test - same issue.
![capture-invalid token](https://cloud.githubusercontent.com/assets/7877635/3267153/80717668-f2c5-11e3-90bf-8241fa685cad.PNG)

**Comment by scynoth** [comment]
I have the same issue. getting an "Invalid Token". I have the system cache disabled
