### ISSUE TITLE
[FR] Better Gantt component

### ISSUE THREAD

**Issue by oparoz** [projectknife/Projectfork#1379]
In the various Open Source PMS written in PHP that I've tested, I mainly see 2 Gantt components being used. The one we have in PF4 and this one [dhtmlxGantt](http://docs.dhtmlx.com/gantt/index.html).
The latter is much more powerful as it's interactive and lets managers properly manage dates, resources and dependencies in that view.

Take a look at those examples
http://docs.dhtmlx.com/gantt/samples/index.html

I haven't looked at the details, but I'm guessing, replacing the old one wouldn't be too difficult in read-only mode (like now), but extra work would be required to make sure tasks are updated when elements are being manipulated in the chart.

I've also found this component: [Twproject Gantt](http://gantt.twproject.com/)
Just like the first one, it's a proper tool to manage tasks and not just a report of some sort. Making modifications (start, length, dependencies) to a task updates the top task (or task-list), other tasks and the project. Per example, if you push back the project by a couple of days, then all tasks will be pushed back. If you push back a task, then its dependencies will also be pushed back, since they can't be started before, etc.
The [demo](http://gantt.twproject.com/distrib/gantt.html) gives a good overview of what's possible to do.

I prefer the look of the first one, but power and ease of integration are more important imho.

**Comment by stuartsmithdesign** [comment]
Has anyone had an update on this topic or any projected release dates? Thanks in advance.

**Comment by beachrider** [comment]
Not yet.Haven't seen any update anywhere else

**Comment by FH4545** [comment]
@angek 

Hi Angek,
I went to your web site today to buy the Gantt Module but saw that you still not have released it. I kindly ask you to give us an update.

Thank you,

Finn

**Comment by BrenDude** [comment]
Hello Angek.

Saw the gantt module video.  Great job.  Is it ready for me to purchase, yet?  
Thanks in advance.

Bren

**Comment by FH4545** [comment]
@angek - As we now can see that you are active again at the Projectfork forum - it would be great to see your update here at this post regarding the Gantt Chart.
Thank you...
Finn
