### ISSUE TITLE
Access Levels

### ISSUE THREAD

**Issue by shiques** [projectknife/Projectfork#1434]
I have created user groups and would like to know how to restrict projects under the usergroup its assigned to. Currently i am still able to access a project that's under a different usergroup.

**Comment by deSpaindeSigns** [comment]
Are you signing in as a Superuser?  I did that when I first set mine up.  I was looking and forgot that I was looking from the perspective of the SuperUser, and not someone who would be restricted to only an assigned group.

Hope that helps!  Seems this is a ghost town....

Jennifer
