### ISSUE TITLE
pf 3d party extension

### ISSUE THREAD

**Issue by archrahul** [projectknife/Projectfork#1442]
really excited about 3rd party pf extension for gantt chart. let me know when it going to publish.

**Comment by stuartsmithdesign** [comment]
Wondering if this is the death of pfextensions and pfgannt? The site has disappeared / been taken down, fingers crossed it isn't, @angek hopefully you could shed some light on this and let us know one way or the other.

**Comment by angek** [comment]
my pfextensions site can now be found at http://pfextensions.angekdesign.com.au and my Gantt Chart package is available for purchase. Check it out at: http://pfextensions.angekdesign.com.au/#pf4gantt
