### ISSUE TITLE
time / hours - Task

### ISSUE THREAD

**Issue by kmbarm77** [projectknife/Projectfork#1451]
Hello everyone ... I have a problem with the option of "time / hours
![tempo](https://cloud.githubusercontent.com/assets/8789343/4807402/6a83233e-5e94-11e4-8c1a-906d6f795506.png)
" run in the tasks. Currently the system provides an estimated time in minutes. How do I insert the calculated time hours? ... I find it very inconvenient to calculate the time in minutes ... I prefer that the calculation is done in hours. How can I make this change? ... Can anyone help me?

**Comment by JamborJan** [comment]
I guess this task can be closed? If there are any other questions about time tracking in hours or minutes, please check this issue: https://github.com/projectfork/Projectfork/issues/267

I'm also waiting for a better solution. But I guess it makes more sense if we all focus on one open issue. Maybe you can close this issue with reference to #267 

Cheers!
