### ISSUE TITLE
Cannot customize date format

### ISSUE THREAD

**Issue by frankfin** [projectknife/Projectfork#1476]
Hello,

I do not find a way to customize the date format in the start- end fields ("Startdatum" and "Frist") of a milestone etc.. Please see the screenshot.
I run Projectfork 4 Pro on Joomla 3.3.6. The Calendar is customized to the Format "d-m-Y" even the "title" that pops up when I move the mouse over the date field shows the date in the right format. What can I do?

Thanks in advance. Kind regards
Frank

![screen-milestone-wrong-date-format](https://cloud.githubusercontent.com/assets/9954653/5193599/19d28ada-7503-11e4-84ea-c1f39ef79c32.jpg)

**Comment by angek** [comment]
Has this been resolved?
