### ISSUE TITLE
Can't get front-end to work properly

### ISSUE THREAD

**Issue by danilodb** [projectknife/Projectfork#1478]
Hi! 
I have installed Projectfork
Joomla Version: 3.3.6 Stable
Projectfork Version: 4.2.2 Stable
PHP Version: 5.4.33

But i have some issues with the frontend concerning mainly file repository.
When I create a subfolder and try to enter in it through front-end the only thing i obtain is a refresh of the page. Next to the subfolder name there is a lock icon but i can't get rid of it, even in the backend.
I have found another issue similar to this on the forum but the solution there was to restore a backup they had on the server.... unfortunately I have no backup :)

I have tried to use Template Goggles found on Projectfork website but nothing changed.
At this moment I have configured the integration Tab in options like this

Load CSS - Yes

Load Bootstrap CSS - Auto

Load Bootstrap JS - Auto

Load jQuery - Site - Auto

Load jQuery - Admin - Auto

User Profile Link - Projectfork

User Profile Avatar - Projectfork

and disabled JqueryEasy and another System Plugin that was using JQuery.

Is there anything else I could try?

Another issue I have is that filenames in frontend are disappearing as soon as I hover them with mouse, but this happened when I tried to change Integration options in order to get things to work.
Thanks!

**Comment by rustle44** [comment]
I had a major javascript confilct with nonumber extensions

After I disabled all PF worked perfectly
