### ISSUE TITLE
"Create Milestone"/"Create Task" does not work 

### ISSUE THREAD

**Issue by frankfin** [projectknife/Projectfork#1479]
Hello there,
In Joomla's Menu Manager I find under "Milestones" a "Create Milestone" menu item. Once I klick in my menu on the link, it right form opens. But if I want to save the new milestone, nothing happens. If I cancel the form I am redirected to a "500" error page.
Exactly the same happens if I use the "create task" menu item.
What can I do?
I run Projectfork 4.2.2.on Joomla 3.3.6.
Thank you in advance.
Kind regards
Frank

**Comment by HelgeSverre** [comment]
- Do you have SEF Url's enabled
- When you open the developer console (press F12 in chrome and Firefox), do you get any red text or error messages in the console tab?
