### ISSUE TITLE
ACL clarification please

### ISSUE THREAD

**Issue by Delemo** [projectknife/Projectfork#1483]
Hi everybody,

I'm a bit confused with my ACL configuration and I'm wondering if someone could provide me some advices.
I'd like to use Projectfork as an intranet (I don't want public user to see anything).
I've created a group for my Organization as a child of Register group.
I've set Permissions of each componant of Projectfork package to allow this new group to Create, Edit, Edit state, Edit own and Delete.
I've created users and assigned them to the new Organization group.
For the moment I've just set menu access level to Organization access level.
All other stuffs (projects, categories, tasks…) are left to Public access level.

It seems to do the trick: people needs to login to access Projectfork dashboard, but I'm not feeling confident, I'm fearing there is a backdoor issue in this configuration.

Is there nothing more to do: set Permissions for each project, changing author…?

Thank you for your help.

Best regards
Simon

**Comment by deSpaindeSigns** [comment]
Hi Simon,

As far as I have seen, there is no other ACL... which really isn't ACL.  It is Joomla ACL and you assign certain groups to certain projects, but controlling permissions on a more detailed level from there does not seem to be available.  It is a bit disappointing.  Hopefully someone will write back to you and prove me wrong!  i also have a question regarding this, so I hope we both get answered!

Jennifer

**Comment by Pakeydev** [comment]
Just found out about this...only Super User group have a permission to add a child Group User. No other way for other user to add it. Administrator can only add a group of  user groups, not a single user group that we created. Any child group will not be in the group selection. So sad to find out about this too late.
