### ISSUE TITLE
"Comments" in project toolbar no translate ...

### ISSUE THREAD

**Issue by wiesiu** [projectknife/Projectfork#1501]
Hello!

I upgrade projectfork to polish language. And all works perfect only one word "Comments" in lower toolbar is no translated (look image). I look in joomla language files but i can't find problem. For help and info about this thanks in advance. Greetings Pawel
![com](https://cloud.githubusercontent.com/assets/7510619/5566807/171adf18-8f34-11e4-98e1-c14f2d0e28fe.JPG)

**Comment by MiesArts** [comment]
I do have the same problem, but now in Dutch. Working with version 4.3.1. 
Does someone know how to solve this, 

Best greetings, 
Mies
