### ISSUE TITLE
Individual tasks in Calendar module?

### ISSUE THREAD

**Issue by oorzaak** [projectknife/Projectfork#1505]
Hi,

As described in an earlier issue, I'd like to use the Calendar module to create an overview of tasks of all our projects in one view (meaning: without selecting a specifiec project). I noticed that when doing this, it is not possible to view individual tasks. Only the last task for a milestone is shown (the one with the latest deadline). Individual tasks are visible only when selecting a specific project. 

Maybe there are good reasons for this, and maybe there are other ways to accomplish what I am looking for. I'd like to hear your advice on this.

Kind regards, Frits

**Comment by angek** [comment]
the calendar module will either:
1/ display all tasks, milestones etc (as per configuration options) if a project has been selected or
2/ display just the project overview of each project if no project has been selected.

To achieve what you require you will need to create a module override. Modifications will need to be made to the module's main helper file and to the files (milestones.php, tasks.php) within the module's helpers sub-directory.
