### ISSUE TITLE
Improvement: Dispaly only own time tracking record sets

### ISSUE THREAD

**Issue by JamborJan** [projectknife/Projectfork#1507]
If a logged in user has only the "edit own" permission for the time tracking component  the listing in the time tracking should:
- have in the filter "author" only one line which is preselected with name of the logged in user
- should display in the list only record-sets of the logged in user

**Comment by JamborJan** [comment]
Since the time until something happens here is longer than it is acceptable I did a dirty hack to get my project done and the time tracking live.

Just in case anybody else needs to limit the front end for the time tracking to display only the record sets of the currently logged in user: replace ```components/com_pftime/views/timesheet/tmpl/default.php``` with this version

https://gist.github.com/JamborJan/b571c82d9e622c5917ad

What I did:
- limit the filer drop down to display only the name of the current user (not really necessary)
- if clause in for each loop to only display current users record sets
- ```$item->created_by == $user->id```are compared to decide which record sets to show

For my needs enough for now but far away from a nice solution. I hope the Projectfork guys are taking a look at the issues and requests which are made here.

**Comment by JamborJan** [comment]
Any news if this can be included in Projektfork?

**Comment by JamborJan** [comment]
@angek you closed a bunch of issues today without any comment. I guess these have not been solved and only the project will be slowly shut down. Or am I wrong?

**Comment by angek** [comment]
@JamborJan take a look at #1813 
I'm here to help. If any of your issues are still relevant please recreate them and I'll address them. 
I just dont have the time to be sifting through issues created so long ago (and for what ever reason were not addressed). Rather spend my time focusing on the here and now.

**Comment by JamborJan** [comment]
Okay cool, thanks for your effort to bring the project back to life!
