### ISSUE TITLE
I am writing an invoicing/billing extension to the time tracking component.... need suggestions

### ISSUE THREAD

**Issue by smoore5527** [projectknife/Projectfork#1509]
I am editing the time tracking component for billing/invoicing, and would like a punch list of features people would like. I'll release it for free once I am done... please peeps, give me your ideas.

**Comment by smoore5527** [comment]
I know that I will put in a column that checks the time log as paid or unpaid... I know I need to assign a user or person as being responsible for said invoice, and I know I need billing information to be attached somehow.

**Comment by smoore5527** [comment]
does it integrate with projectfork?

**Comment by mbsarino** [comment]
no but i would think it may be easier and faster to work on the integration than to develop an invoice system from the ground up.

**Comment by smoore5527** [comment]
Well the reason I am doing it is #1. because i have the need, but #2, because I am learning how to develop and I imagine building something from the ground up would be a good way to learn

**Comment by micker** [comment]
maybe a automatique email with invoice in pj
