### ISSUE TITLE
I want contractors to only track time and mark tasks complete

### ISSUE THREAD

**Issue by deSpaindeSigns** [projectknife/Projectfork#1510]
Currently, all users who have permissions to see ProjectFork on the frontend can add projects, task, etc..  I want only SuperUsers to be able to add anything.  I want my contractors to be able to do everything a SuperUser can do, EXCEPT add Projects, Tasks, Milestone, etc.  

So, I create, they tell me if they did it and how long it took them.  Commenting, forum, design submissions, time tracking, and marking tasks as complete are prefect for them to do.  But I want to be the only one to add anything like a project or task, since I am the project manager.

Is that possible?  I haven't found anything regarding that in documentation.

For background on my current settings.... ProjectFork is only visible if the user is logged in.  Projects are only visible to users who are part of groups that have permissions to view those individual projects.  

Thanks!  If you need any clarification let me know!

Jennifer

**Comment by rustle44** [comment]
You can restrict access with the Joomla menu manager

**Comment by deSpaindeSigns** [comment]
Thank you.  The problem with that is that I am not trying to restrict menu items.  I am trying to restrict what certain users can do while on the pages.  For example, I want them to be able to view the Projects page, but I don't want them to be able to add a new project.  Only I (a Super user) should have that right in the component.

This seems a bit obvious that certain users should be restricted as to what they can and cannot do.  I don't want my content writers to add a task for my template designers, or delete their own task by accident.

But, as you can see, I still need them to be able to access all the pages.  They just have restrictions as to what they are allowed to do once on those pages.

Is this possible??

Jennifer

**Comment by rustle44** [comment]
Hi Jennifer - yes you need the menu manager to restrict access to the add/edit pages

Create a new menu called 'Project Manager Tools' or whatever
then add menu items which point to those tasks, for example :
Project Fork--> Task --> Create A Tasklist
and restrict this page to the appropriate user groups

Now if you want to restrict individual links or buttons, you would have to do this with a template override, using .php or javascript on each page by adding a function to query the user access and display those link/buttons based upon access levels
