### ISSUE TITLE
Not showing all tasks

### ISSUE THREAD

**Issue by cyberrick** [projectknife/Projectfork#1514]
When I view a project in the fronend I can see all tasks when logged in as SuperUser.  When I log in as  my client, it only shows  tenth of the number of tasks that should be there.  I have checked and re-checked all the permissions and from what I can see the client should be seeing all the tasks in all the milestones. When I created the tasks I didn't use a task list.  Would that make a difference?

**Comment by chantas** [comment]
My comment may be stupid, but did you check also the permission of the correcponding milestone and project for a non-showing task?

**Comment by cyberrick** [comment]
Not at all.  I need all the help I can get.  I assumed that the permissions set in the project was passed along to the rest of the system, (milestones, tasks, design, etc).  I try and check the individual milestones and tasks I guess, but that seems like a real pain to have to do each time.

**Comment by chantas** [comment]
You can easily have an overview of the permission for each in the back-end. Changing them now will be a pain, but setting them when creating a project is just one click to do... 

Check all permissions, and if everythig is correct, then you will have learnt that 1/ permissions are passed along and 2/ it was not the problem!
