### ISSUE TITLE
Redirection after project filter

### ISSUE THREAD

**Issue by miclortie** [projectknife/Projectfork#1515]
Hi, 

I have a menu item that points to the repository. When I click on that menu item on the front end, the repository shows the proper files from the current project. When I click on the project filter and select another project, PF redirects to another page. Because I have my menu to be shown on only certain page, this redirection to a random PF page makes my menu disappear and my users need to retype the url of my website in order to have access to the normal website.

Any idea? Thanks

**Comment by angek** [comment]
care to share a link so I can take a look?
