### ISSUE TITLE
Linking the result of a form made in RS-forms to fields in PF

### ISSUE THREAD

**Issue by DiGwork** [projectknife/Projectfork#1540]
I would like to create a form using RS-Forms to offer managers that need to give a project team a brief.
The brief consists of a task list with multiple tasks all for the same Milestone.
Eg a Manager fills in the form.
      The form then creates a Task List with Tasks that falls under a specific Milestone in a specific Project in PF.

I need this as not all contributors to a project are as computer literate and don't need all the options available and the complex settings offered by PF when creating a task. I need to dumb down their input interface for them so that they are only asked for the input they need to contribute.
In my case it is:
Select the project
Select the Milestone
The task list is automatically populated with a standard name using their username (eg "Adele's Brief") with an option for them to change to other if there is a special name for task list
       (logic asks if the list already exists in that Milestone if it does it does not create a new list just adds task to the existing list)
They then enter a name for the new Task "product request" = Name
They  enter a set of instructions = Description (No text formating to keep it simple)
They Upload a sample image = also inserted into = Description
They select a date for when materials will be ready = Start Date 
They select deadline = End Date
Then submit
This seems a very simple thing but noone has been able to help me do this.
Sure it is just a linking fo Database fields but as I did not develop PF I have no idea what the fields are and what instruction I would have to build into the RS-Forms form to deliver the result.

**Comment by HelgeSverre** [comment]
Do you have RSForm! Pro or the free version?

I have done a few integrations between RSForm and ProjectFork for my employer and I could assist you in creating this integration.

There are only one really reliable way to do this, and that is via the "PHP Scripts" feature in RSForm! Pro, in which you can grab the form data and put it into the respective tables in ProjectFork.

I do unfortunately have to charge a fee of **$150 USD** for this integration, if you're interested in moving forward, hit me up via [email](mailto:email@helgesverre.com) or my [contact form](https://helgesverre.com/contact.php).
