### ISSUE TITLE
Task Details View:  different color / symbol if task is completed

### ISSUE THREAD

**Issue by enzo01** [projectknife/Projectfork#1576]
Hi,

In the task details view, start date and Deadline is colored in red, even if the task is completed.
Is it possible to change the color and symbol if the task is completed

I also tried to add a "Task finished entry" by adding the following in tasks/tmpl/default.php, but I don't get the item->complete entry

```
            <?php
            if ($item->complete) {
                echo 'Yes';
        } else {
            echo 'No';
        }
         ?>
```

thanks
enzo

**Comment by DiGwork** [comment]
I must agree this would be helpful to see a completion date and possibly the start and deadline no longer in red unless the completion date was after the deadline then showing it in red might help show late deliveries.
