### ISSUE TITLE
Project Fork - New Feature

### ISSUE THREAD

**Issue by bokigto** [projectknife/Projectfork#1587]
What new feature is in plan for next release?

Recurring tasks?
Custom Fields?
ETC.  
Do we have a timeline?

thanks

**Comment by Coodr** [comment]
Yes, especially custom fields for projects and tasks are great demand.
Any infos about next release (date, features)?

Thx for your great work!

**Comment by wlukas84** [comment]
Custom Fields for Projects and Timesheet! Big Please!!!!

**Comment by micker** [comment]
% In task please
