### ISSUE TITLE
PROBLEM TO ADD  MILESTONE - FRONT END

### ISSUE THREAD

**Issue by todosoft** [projectknife/Projectfork#1599]
Hi i have a situation in the FRONT END i cannot add a new Milestone because i cannot assign to a specific project.

When i tried to add a new milestone, the form asked me to assign it to a project, but the form dont show the project that are listened.
The only way to do it is from the back!!

Any idea?

Thanks a lot!

**Comment by eaxs** [comment]
Seeing how your gantt chart isn't working either, I think it's safe to say that there's a javascript issue somewhere on your site. The chart and the project select list aboth require jQuery to be loaded correctly.

I suggest you try the following in the backend:
* Go to: Components -> Projectfork -> Options -> Inegration
* Set  Load jQuery - Site	to "No"

This may or may not help. If it does not work, please set that option back to "Auto". 
Please let me know which version of Joomla and the template you are using. You can also check your template configuration to see if there is an option for enabling/disabling jQuery - That's typically found in Joomla 2.5 templates.

**Comment by todosoft** [comment]
Hi thanks for your help, it cannot work. I attach a printscreen so you can know what i meaning.

About the PHP version is: 5,3 and Joomla version is: 2.5.8

I read about minimun requirement and we are OK
![projectfork](https://cloud.githubusercontent.com/assets/12235547/7484709/334b815a-f362-11e4-81d2-52cc22c33043.png)

Regards

**Comment by eaxs** [comment]
I see what the problem is there. Looks like I have to roll out a patch for the template in order to fix it. I'll make sure to release a patch later today or tomorrow.

Thanks!

**Comment by todosoft** [comment]
Thanks for your help, please tell me when you release it, and I appreciate if you explain to me how i apply this patch

Regards

Alejandro

**Comment by todosoft** [comment]
Hi any news about the problem that i told you? Thanks a lot

**Comment by eaxs** [comment]
Yes sorry. There is a new version of the AppTheme template available on the site. Please install it and everything should work again. Also, make sure you configure project as shown below when using this template:

![screen_joomla 2 5 28 - administration - dashboard_12_55_06](https://cloud.githubusercontent.com/assets/489521/7609049/58f77c16-f96f-11e4-83e8-0006e65a1bf6.jpg)
