### ISSUE TITLE
Time in Tasks

### ISSUE THREAD

**Issue by ghardin26** [projectknife/Projectfork#1607]
When creating tasks, the rate is set as an hourly rate, but the estimated time and actual time in Time Tracking must be entered in minutes.  Very confusing for users!  Estimated time and actual time should be able to be entered in hours including fractions of an hour.  IE 1 hour equals 60 minutes, 1.5 hours equals 90 minutes

**Comment by JamborJan** [comment]
Please check this issue: https://github.com/projectfork/Projectfork/issues/267

A small improvement is mentioned there. I'm also waiting for a better solution. But I guess it makes more sense if we all focus on one open issue. Maybe you can close this issue with reference to #267 

Cheers!
