### ISSUE TITLE
Template compatibility issues

### ISSUE THREAD

**Issue by jhweb** [projectknife/Projectfork#1616]
Hi there,

I've been using the Apptheme and goggles template for projectfork. However the problem comes in with using other components which I want to display on one template and not too mention all the additional features for using a warp or any other template provider..  

The biggest problem is this bootstrap issue that none of the templates I tested worked with PF. Like with YT warp & JA T3 templates - the tabs in create new -view does not work. As well as a few other small issues of expand/collapse & on/off types of buttons. 

I couldn't find any other joomla template that could work with PF. 
Is there any way of correcting these 'minor' issues? 

BTW. I tried toggling PF bootstrap & jquery settings and the template settings with no results.

Any help would be much appreciated.
Thank you.
jh

**Comment by sarrene** [comment]
I also am curious on this. We are merging our sites for a better workflow, and have issues as well. I am using Vertex based template from Shape5. I have tried others as well, and same issue. 
Start Date:
Deadline:
Created By:
Labels:
Non of those are displayed for us. Any help or hope on getting this working or assistance to us on how to get other templates to work?

**Comment by sarrene** [comment]
Is there any update to this problem?
It occurs even with joomla's default templates.
