### ISSUE TITLE
mouse over

### ISSUE THREAD

**Issue by dudimills** [projectknife/Projectfork#1637]
hi,

when i'm hovering with the mouse over the tasks on the gartt chart the tasks vanish. 

any fix for that?

**Comment by albertotoplevel** [comment]
I am facing the same issue, not only in gantt tasks but also on start date and deadline, on Projects page. After hovering, the information dissapears. I have to reload the page to have the information back.

**Comment by albertotoplevel** [comment]
It seems they do not care about support. But I have paid to have pro version. I will post a negative review in JED as I not getting event a simple answer.
