### ISSUE TITLE
Assign Single User from Drop Down Menu Per Project

### ISSUE THREAD

**Issue by MisterBad** [projectknife/Projectfork#1660]
Hello,

I have scoured all forums to try and find this solution. I can appreciate the ACL group aspect. However, considering the nature of various business models, some projects only require ONE user if your business model is that of freelancer management.

I understand I can create a new group/team for each project, but why is it impossible to assign a single user to a project? There has got to be a hack or plugin to make this direct link.

I manage SINGLE user projects for various "groups" of users. I don't want all of them to see each others projects, just want them to see and update progress collaboration with only me, their manager aka Super Admin on their project. As a "Manager" I create and manage time restraints and workflow they, MY CLIENTS WHOM I MANAGE, should be able to report on milestones, tasks completion etc, not really create edit the projects.

I already have multiple "groups" ie: Engineers, Asst. Engineers, etc etc.

I need to be able to assign a specific project to an individual (rarely multiple) within these groups. If not, then as much as I love PF it will just be too time consuming and may consider using Fabrik as it is totally customizable although I have to build it from scratch. But the fact that this seemingly small option is not available without jumping through hoops etc in this great component... there has to be a solution.

Thanks for your time and consideration.

Regards.

Mr. B

So please, I am begging you, there has got to be away.

**Comment by ozwest** [comment]
Hello

I have just installed Projectforuk 4.3 also with the view that I would be able to assign users to a project rather than a whole group.

I want to use Projectfork to work with some clients, keeping the exchange of documents and ideas in one place rather than all over emails.

Is there a solution to this?

Thank you.

**Comment by gridfree** [comment]
I am getting a developer to add this to the component, I am not sure how to offer this to projectfork community
