### ISSUE TITLE
What's the latest news with Project Fork????

### ISSUE THREAD

**Issue by EdgyLedgyWedgbarge** [projectknife/Projectfork#1666]
Could someone let us know what is happening with Project Fork?
I was just looking through all the posts on this so-called "Support" section of Project Fork and not a single post seems to get answered any more (or at least for the last 3 months).

Is this now dead? or are the plans to take it any further?

Some kind of response would be appreciated.

**Comment by FH4545** [comment]
@EdgyLedgyWedgbarge - I wish I could give you a firm update but the only one who can do this is @eaxs 

At this post you can read about the discussion I started regarding the future of Projectfork - I did the last post in this discussion in May-15 - https://github.com/projectfork/Projectfork/issues/1511#issuecomment-70533361
