### ISSUE TITLE
Change status of task shows script above module

### ISSUE THREAD

**Issue by dustynsaint** [projectknife/Projectfork#1673]
When I change the status of a task I'm seeing scripting appearing above the module e.g. "
 {"success":"true","messages":["COM_PFTASKS_N_ITEMS_UPDATED"]}"
Running joomla 3.4.4, PF4.3.2 and php 5.3.28

**Comment by angek** [comment]
@dustynsaint is this happening on the front or back end?
I've tried with both and can't reproduce the issue.

**Comment by dustynsaint** [comment]
It's showing on the front end

**Comment by dustynsaint** [comment]
Hi, can you shed any further light on this?  Please email me directly if you need details of the site to look directly at it....

Dustyn
