### ISSUE TITLE
Group Creation

### ISSUE THREAD

**Issue by ptruble** [projectknife/Projectfork#1693]
I am inquiring on progress in allowing site users to create their own project groups and assign users to those groups to the frontend?  This is a key requirement for our company to utilize ProjectFork.

**Comment by gagnonjeanfrancois** [comment]
Hello,
Like you, I am a ProjectFork user and I have no connection with the development team ... I am convinced it would be a nice feature, but my little fingers think it will not be a priority and it could take a few years to see. I would like, once again, to emphasize that my little finger have no relationship with the development team ;) . 

If you're in a hurry, and you have the experience and the motivation to learn to CCK, Fabrikar can help you in this task : http://fabrikar.com/  .

Hoping that my answer will help you
