### ISSUE TITLE
Project Milestone title, moving it next to checkbox

### ISSUE THREAD

**Issue by mattgaiser75** [projectknife/Projectfork#1712]
Hello!  I would love to move the Milestone Titles display up one line and next to/to the right of the checkbox (see attached screenshot)  Would GREATLY appreciate being pointed in the right direction.. thanks!

![screen shot 2016-02-22 at 6 34 27 pm](https://cloud.githubusercontent.com/assets/16749399/13236545/17e486ba-d993-11e5-8d2f-a5a973c53bcc.png)

**Comment by angek** [comment]
have you tired adjusting the margin css settings for .com_pfmilestones h4 ?
