### ISSUE TITLE
Loosing titles or other tools at frontend

### ISSUE THREAD

**Issue by Otenkus** [projectknife/Projectfork#1767]
Hi, when i move the cursor on some items at frontend, items are disappearing from the screen after i pass over them with my mouse. I tried IE 11, Chrome and Yandex browsers but the results are same.

Is there any solution for avoiding this issue?

![pf_1](https://cloud.githubusercontent.com/assets/20453220/16830389/4b3a6172-49a7-11e6-9687-9aaabc48735b.JPG)
![pf_2](https://cloud.githubusercontent.com/assets/20453220/16830390/4b5a7296-49a7-11e6-9b56-3532e3319704.JPG)

**Comment by jhonca** [comment]
Hi,
You could solve this problem? I have it too
