### ISSUE TITLE
Attach documents instead of files

### ISSUE THREAD

**Issue by pulsarinformatique** [projectknife/Projectfork#1784]
Hi

We are looking to add documents to projects instead of files. Therefore do you have a plugin to attach docman or (even better) JoomDoc documents to PF projects ?

In other words how can we attach third party contents to a project? Should we just write a plugin ? how ?

thanks

cyril

**Comment by pulsarinformatique** [comment]
Hello

I can't get any info on the https://www.projectfork.net/ or the https://www.facebook.com/projectfork pages. 
How can we get in touch with someone please?
thanks

cyril

**Comment by angek** [comment]
@pulsarinformatique Im reaching out (see #1813) to see if you still need clarification.
For what it's worth, Projectfork does not integrate with any 3rd party document management extension and you would need to get a developer to create such an integration for you.
