### ISSUE TITLE
Calender Manual Mode not showing Created Projects

### ISSUE THREAD

**Issue by lemollon** [projectknife/Projectfork#1797]
I created separate projects and I'm trying to set calender's for the specific project through manual mode but its not showing any of the projects in the drop down list

**Comment by lemollon** [comment]
![capture](https://cloud.githubusercontent.com/assets/24685088/21659352/ebfd28bc-d28f-11e6-902a-8135341c3d3f.PNG)

**Comment by lemollon** [comment]
I've been racking my brain on this one and I cant figure it out. Assistance is greatly appreciated.

**Comment by angek** [comment]
@lemollon I know this is old... Im just trying to lend a hand (see #1813)
There must be a javascript conflict that's preventing the select2 from populating. Ive tested this on a vanilla Joomla 3.7.4 with PF 4.4.0 and have no such issues.
