### ISSUE TITLE
Can not give access to Projectfork component on backend to new user group.

### ISSUE THREAD

**Issue by Romerski** [projectknife/Projectfork#1800]
Hi, im trying to give access to the whole Projectfork components on a new user I've created. 

I created a new user group 'Projects admin', then gave 'Special' access level. Afterward, I gave all permisions to the new user group in 'Components > Projectfork > Projects' (and on all projectfork components) but im not able to have access to Projectfork component on new user's backend. 

What I want is to have an user who can only administrate the whole Projectfork components in the backend without having access to other components, modules, etc. It only appears 'System' and 'Help' in the backend menu and not 'Components' with Projectfork as it should be.

I basically followed this tutorial https://www.projectfork.net/docs/15-basics/40-groups-and-permissions

Any help? Thanks and sorry for my englando.

**Comment by angek** [comment]
hey @Romerski for what it's worth, the Projectfork component doesn't provide the necessary ACL to accomplish this.
