### ISSUE TITLE
Group restriction / assign to individual project 

### ISSUE THREAD

**Issue by bahaaeldin** [projectknife/Projectfork#1803]
I want to use Project Fork to allow users to have their own projects, and be able to assign other users. I dont want other, unassigned users, to have access to a project they arent assigned to.

Is there a way to accomplish this? and how to I do this?

**Comment by jeimsbond** [comment]
Hello
I have two questions about this component;
- the first time you want to get the Spanish version always takes me to transifex but I can not download the language and I do not see any other site. If anyone has this translation I would appreciate it.
- The next is that someone knows if you could manage the projects in different ways for different people or groups individually without the users accessing the content of others. From what I see the component does not seem to give that option, I find it interesting to manage projects from several clients but you can not see each other.

**Comment by jeimsbond** [comment]
Hi wscottchris, I already saw how to do it. Thanks for your help
