### ISSUE TITLE
Getting Error when saving from site

### ISSUE THREAD

**Issue by wscottchris** [projectknife/Projectfork#1805]
When I am saving info from the site, not administrator, area, I get the following error:

Error displaying the error page: 
Table 's' was not locked with LOCK TABLES SQL=SELECT id, home, template, s.params FROM #__template_styles as s LEFT JOIN #__extensions as e ON e.element=s.template AND e.type='template' AND e.client_id=s.client_id WHERE s.client_id = 0 AND e.enabled = 1: Table '#__pf_projects' was not locked with LOCK TABLES SQL=SELECT `alias` FROM `#__pf_projects` WHERE id = 8

The information is saved, but this error is thrown.

Joomla Version: 3.6.4 Stable
Projectfork Version: 4.4.0 Stable
PHP Version: 5.4.45

We have tested with SEF both on and off
How do we resolve this issue?

**Comment by angek** [comment]
hey @wscottchris is this still an issue for you?

**Comment by angek** [comment]
works for me.
tested with Joomla 3.7.4 and PF 4.4
