### ISSUE TITLE
Calendar error in Joomla 3.7.2

### ISSUE THREAD

**Issue by AyelGoth** [projectknife/Projectfork#1810]
When I try to update the date of a project, task or milestone, joomla gives an error that says: An error has occurred. 500 default Presentation not found.
![captura](https://cloud.githubusercontent.com/assets/5136303/26387277/a54afdc6-4022-11e7-92d5-c6659d10c1c5.jpeg)

**Comment by angek** [comment]
Hey @AyelGoth do you still require help with this?

**Comment by angek** [comment]
Works for me.
tested with Joomla 3.7.4 and PF 4.4 and was unable to reproduce error.

**Comment by AyelGoth** [comment]
In Joomla 3.7.4 I do not see the error. Apparently it was a joomla 3.7.3 bug

2017-07-30 19:06 GMT-03:00 angek <notifications@github.com>:

**Comment by AyelGoth** [comment]
In Joomla 3.7.4 I do not see the error. Apparently it was a joomla 3.7.2 bug

**Comment by angek** [comment]
nice! and thank you for the reply :)
