### ISSUE TITLE
Filter to Limit number of tasks displayed. 

### ISSUE THREAD

**Issue by RakshithAthreaysR** [projectknife/Projectfork#1811]
Hi all,

By default all the tasks are displayed when we have selected certain project. But I need to restrict/limit it to display only few tasks ex: only 10, only 20 ...so on. The same option which is already there in other places.

Thanks

Rakshith

**Comment by angek** [comment]
@RakshithAthreaysR have you sorted out your pagination issues or do you still need help?

**Comment by RakshithAthreaysR** [comment]
@angek

Thank you for your response. Yea I need your help, can you please help me out on the same.

Thanks in the advance,

**Comment by angek** [comment]
Projectfork uses Joomla's default list limit configuration setting for pagination.
So if, under Global Configuration ->Site Settings you have the default list limit set to 20 then Projectfork will use this value to limit the number of items displayed in all it's lists. 
Of course, as a user who is interacting with the site, you change the list limit ( eg from the tasks list page) this will update the list limit for the user during the active session.

Does that make sense?

**Comment by RakshithAthreaysR** [comment]
Yea ......But, say when you are within specific project........ all the tasks related to project is being displayed. Here is where i need the limit to apply as well. To restrict it to the required limit(5, 10, 20, 25 ..............).
Same in Milestones ...etc .....

**Comment by angek** [comment]
Is it possible to get a login to your site so I can take a look? a normal registered user account will suffice.
You can send details to angek[at]angekdesign[dot]com[dot]au

By default, those lists should be limited to whatever your global list limit is set to.

**Comment by angek** [comment]
@RakshithAthreaysR sorry, I misunderstood you. I can confirm that the list limit is not being applied when viewing tasks while in a project workspace. Will get a fix for you soon.

**Comment by angek** [comment]
@RakshithAthreaysR Ive had a look at the code and see that pagination is explicitly prevented in list views when you are in a workspace. It is only allowed when in the global workspace.

This bit of code found in /components/com_pftasks/views/tasks/tmpl/default.php starting at line 410 clearly forbids pagination when you have a project filter applied.

`            <?php if (!$this->state->get('filter.project')) : ?>
                <div class="filters center">
                    <span class="display-limit">
                        <?php echo $this->pagination->getLimitBox(); ?>
                    </span>
                </div>
            <?php endif; ?>`

**Comment by angek** [comment]
hey @RakshithAthreaysR can you please try the following fix (make sure you backup first :) ):

open the following file:
`/components/com_pftasks/views/tasks/tmpl/default.php`

go to line: 410 and replace this block of code:

```
<?php if (!$this->state->get('filter.project')) : ?>
                <div class="filters center">
                    <span class="display-limit">
                        <?php echo $this->pagination->getLimitBox(); ?>
                    </span>
                </div>
            <?php endif; ?>
```
with this:

```
                <div class="filters center">
                    <span class="display-limit">
                        <?php echo $this->pagination->getLimitBox(); ?>
                    </span>
                </div>
```
now open the file:
`/components/com_pftasks/models/tasks.php`

go to line 227 and just under `public function getItems()` you will find the following bit of code:
```
        // Get a storage key.
        $store = $this->getStoreId();

        // Try to load the data from internal storage.
        if (!isset($this->cache[$store])) {
            // Load the list items.
            $limit = ($this->getState('filter.project') ? 0 : $this->getState('list.limit'));
            $query = $this->_getListQuery();
            $items = $this->_getList($query, $this->getStart(), $limit);

            // Check for a database error.
            if ($this->_db->getErrorNum()) {
                $this->setError($this->_db->getErrorMsg());
                $this->cache[$store] = false;
            }
            else {
                // Add the items to the internal cache.
                $this->cache[$store] = $items;
            }
        }

        $items  = $this->cache[$store];
```

and replace it with:

```
/*
        // Get a storage key.
        $store = $this->getStoreId();

        // Try to load the data from internal storage.
        if (!isset($this->cache[$store])) {
            // Load the list items.
            $limit = ($this->getState('filter.project') ? 0 : $this->getState('list.limit'));
            $query = $this->_getListQuery();
            $items = $this->_getList($query, $this->getStart(), $limit);

            // Check for a database error.
            if ($this->_db->getErrorNum()) {
                $this->setError($this->_db->getErrorMsg());
                $this->cache[$store] = false;
            }
            else {
                // Add the items to the internal cache.
                $this->cache[$store] = $items;
            }
        }

        $items  = $this->cache[$store];
*/
        $items  = parent::getItems();
```

let me know if that solves the pagination issues so I can mark it for inclusion into the next minor release.

**Comment by RakshithAthreaysR** [comment]
Hi @angek ,

I'm sorry for my late reply, Thank you so much for the solution. I'll implement the same and let you know how it works.
Thanks again.

**Comment by RakshithAthreaysR** [comment]
hi @angek 
I am getting white screen of death once i make those changes. Can you please check once and let me know

**Comment by angek** [comment]
hey @RakshithAthreaysR, I committed the changes to the repo.
download them from:

https://github.com/projectknife/Projectfork/blob/33ad3ab12cc6826884c6ed7125ce5e8a65d605c0/source/components/com_pftasks/site/models/tasks.php

and

https://github.com/projectknife/Projectfork/blob/33ad3ab12cc6826884c6ed7125ce5e8a65d605c0/source/components/com_pftasks/site/views/tasks/tmpl/default.php

**Comment by RakshithAthreaysR** [comment]
Hi @angek 
Working as per the requirement, Great work.
Thank you so much.

**Comment by angek** [comment]
My pleasure!
