### ISSUE TITLE
Tasks Access/View/List only to Creator and Assigned Users

### ISSUE THREAD

**Issue by lezabour** [projectknife/Projectfork#392]
Hi,
I would like to change something is the Taks listing and viewing system.
Is it possible to have only the Creator and the Assigned user to see the task?
Is there a configuration or a hack that can do that?
thank for your help

**Comment by dungvietnam** [comment]
I want the Same.. 
- Creat Project on Front End.. and  Assign User A, User B and Only User A vs User B view Project and Task
