### ISSUE TITLE
Can't Delete a Task List

### ISSUE THREAD

**Issue by jrseliga** [projectknife/Projectfork#702]
Two issues:
1. It is not possible to delete a task list from the frontend
2. If a task list doesn't have any tasks associated with it, it is not visible in the frontend.
- Even if the you could trash a task list, how do you trash something that isn't visible?
- Therefore a task list should always be visible.

**Comment by guthubbenutzer** [comment]
Hello
deleted my task lists via phpMyAdmin. Worked like a charm!
