### ISSUE TITLE
Week days in Gantt not translatable !?

### ISSUE THREAD

**Issue by peterromao** [projectknife/Projectfork#737]
As one may confer from the image below the week days aren't getting translated which is only normal as they were not present in the language file of the module anyway.

Where are these capital letters defined or used in the code or is this going to be addressed in the near future?

![image](https://f.cloud.github.com/assets/5205836/982406/af0f2052-07ec-11e3-9e57-30521cd484e8.png)

**Comment by maxgdias** [comment]
Great !! Thanks! Work perfect!
