### ISSUE TITLE
where to download french language package for projectfork ?

### ISSUE THREAD

**Issue by gpweb** [projectknife/Projectfork#853]
hi, 
Please, how can i download french package complete ?

i registered in Transifex, but can't find totally package to download ....

Sorry, 

thanks
a lot

**Comment by baijianpeng** [comment]
hi, @kyleledbetter , do you mean we have to click and click and click and click ... for more than 40 times to download a language? Why not just pack and merge them into the ProjectFork installer package?

Thank you.
