### ISSUE TITLE
Calendar?

### ISSUE THREAD

**Issue by marcodeluca** [projectknife/Projectfork#878]
Hey guys - 

Im going to be investing some time and money on a calendar for a site that uses projectfork. Is the calendar in the pipeline for you? If it is... got a rough estimate for release? If it isn't... maybe you'd be interested in what we come up with. If you have any comments or suggestions, let me know. I need to get mine up and running by January, so I'll probably have a couple guys work on it full time next month.

**Comment by Srinivas37** [comment]
We want to get the user based listing, Suppose when the person logs in, he should get the listings of his task, projects, milestones, timesheet through menu items as My Projects,My Tasks, My Milestones, My Timesheet, My Calendar, My Repository etc
How we can get these listings??. What we need to do for that??


Regards:
Srinivas
